// JwtPayload maps the claims generated by AuthController.GenerateToken()
// Claim("id", ...) -> "id"
// ClaimTypes.Name -> "unique_name" (standard JWT mapping)
// ClaimTypes.Role -> "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
export interface JwtPayload {
  id: string;
  unique_name: string;
  'http://schemas.microsoft.com/ws/2008/06/identity/claims/role': string;
  exp: number;
  [key: string]: string | number; // allow index access for dynamic claim lookups
}

export function decodeJwt(token: string): JwtPayload | null {
  try {
    const base64Url = token.split('.')[1];
    const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    const json = decodeURIComponent(
      atob(base64)
        .split('')
        .map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
        .join('')
    );
    return JSON.parse(json) as JwtPayload;
  } catch {
    return null;
  }
}

/** Get display name from JWT — tries unique_name first, falls back to id */
export function getNameFromJwt(token: string): string {
  const payload = decodeJwt(token);
  if (!payload) return 'My Account';
  return payload['unique_name'] || `User #${payload['id']}`;
}

/** Get user ID from JWT */
export function getUserIdFromJwt(token: string): number {
  const payload = decodeJwt(token);
  return payload ? +payload['id'] : 0;
}

/** Get role from JWT */
export function getRoleFromJwt(token: string): string {
  const payload = decodeJwt(token);
  if (!payload) return '';
  return String(payload['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] || payload['role'] || '');
}
